

// create customer
POST http://localhost:3000/customers HTTP/1.1
content-type: application/json

{"customerId": 6, 
"customerName": "Sinisa Neskovic", 
"customerEmail": "sinn@itu.dk"}
###

// get customer by id
GET http://localhost:3000/customers/6 HTTP/1.1

###

// get all products
GET http://localhost:3000/products HTTP/1.1
###

//get product by id
GET http://localhost:3000/products/1 HTTP/1.1
###

//get all product categories
GET http://localhost:3000/productCategories HTTP/1.1
###

//get all products from a specific category
GET http://localhost:3000/products/productCategories/green HTTP/1.1
###

//get all products from a specific category
GET http://localhost:3000/products/productCategories/conventional HTTP/1.1
###

// create basket for a specific user 
POST http://localhost:9000/baskets HTTP/1.1
content-type: application/json

{"customerId": 746, "products": []}

###

// add a specific product in a specific customers basket
POST http://localhost:9000/baskets/1000/products HTTP/1.1
content-type: application/json

{"productId": 4}

###

// get content of basket for a specfic user
GET http://localhost:9000/baskets/746/products HTTP/1.1

###
// delete specific product in a specific customer basket 
DELETE http://localhost:9000/baskets/765/products/12 HTTP/1.1

###
